force-app/main/default/objects/AsyncFunctionInvocationRequest__c/AsyncFunctionInvocationRequest__c.object-meta.xml
<CustomObject>
    <label>Async Function Invocation Request</label>
    <nameField>
        <displayFormat>AFIR-{0000}</displayFormat>
        <label>AsyncFunctionInvocationRequest Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Function Invocation Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AsyncFunctionInvocationRequest__c/fields/Callback__c.field-meta.xml
<CustomField>
    <fullName>Callback__c</fullName>
    <label>Callback</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AsyncFunctionInvocationRequest__c/fields/CallbackType__c.field-meta.xml
<CustomField>
    <fullName>CallbackType__c</fullName>
    <label>CallbackType</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/AsyncFunctionInvocationRequest__c/fields/RequestId__c.field-meta.xml
<CustomField>
    <fullName>RequestId__c</fullName>
    <label>RequestId</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AsyncFunctionInvocationRequest__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AsyncFunctionInvocationRequest__c/fields/StatusCode__c.field-meta.xml
<CustomField>
    <fullName>StatusCode__c</fullName>
    <label>StatusCode</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FunctionReference__mdt/FunctionReference__mdt.object-meta.xml
<CustomObject>
    <label>Function Reference</label>
    <pluralLabel>Function References</pluralLabel>
</CustomObject>

force-app/main/default/objects/FunctionReference__mdt/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/functions/tests/AsyncResponseHandlerTriggerHandlerTest.cls
/**
 * Tests for AsyncResponseHandlerTriggerHandler.
 */
@isTest
public class AsyncResponseHandlerTriggerHandlerTest {

    @isTest
    static void testHandle_noResponseYet() {
        AsyncFunctionInvocationRequest__c afir = new AsyncFunctionInvocationRequest__c(
            StatusCode__c = 201
        );
        List<AsyncFunctionInvocationRequest__c> afirs = new List<AsyncFunctionInvocationRequest__c>();
        afirs.add(afir);
        List<AsyncFunctionInvocationRequest__c> afirCallbacks = AsyncResponseHandlerTriggerHandler.handle(afirs);
        Assert.isTrue(afirCallbacks.isEmpty());
    }

    @isTest
    static void testHandle_invalidCallback() {
        AsyncFunctionInvocationRequest__c afir = new AsyncFunctionInvocationRequest__c(
            StatusCode__c = 200
        );
        List<AsyncFunctionInvocationRequest__c> afirs = new List<AsyncFunctionInvocationRequest__c>();
        afirs.add(afir);
        List<AsyncFunctionInvocationRequest__c> afirCallbacks = AsyncResponseHandlerTriggerHandler.handle(afirs);
        Assert.isTrue(afirCallbacks.isEmpty());
    }

    @isTest
    static void testHandle_invokeCallback() {
        String acctName = 'testHandle_invokeCallback-' + Datetime.now().getTime();
        FunctionInvokeTests.FunctionTestCallback callback = new FunctionInvokeTests.FunctionTestCallback(acctName);
        FunctionReference__mdt funcRef = new FunctionReference__mdt(Endpoint__c = '');
        Function function = new Function('', '', funcRef);
        String callbackType = function.determineClassType(callback);
        Assert.isFalse(String.isEmpty(callbackType));
        AsyncFunctionInvocationRequest__c afir = new AsyncFunctionInvocationRequest__c(
            Id = Id.valueOf(AsyncFunctionInvocationRequest__c.SObjectType.getDescribe().getKeyPrefix() + '000000000000'),
            Callback__c = JSON.serialize(callback),
            CallbackType__c = callbackType,
            RequestId__c = 'RequestId',
            Response__c = 'Response',
            StatusCode__c = 200
        );
        List<AsyncFunctionInvocationRequest__c> afirs = new List<AsyncFunctionInvocationRequest__c>();
        afirs.add(afir);

        Test.startTest();

        List<AsyncFunctionInvocationRequest__c> afirCallbacks = AsyncResponseHandlerTriggerHandler.handle(afirs);
        Assert.isFalse(afirCallbacks.isEmpty());

        Test.stopTest();

        // Validate callback invocation
        Account acct = [SELECT Id, Name, Description FROM Account WHERE Name =:acctName];
        Assert.isNotNull(acct);
        Assert.isNotNull(acct.Description);
        Assert.isTrue(acct.Description.contains(afir.Response__c), acct.Description);
    }
}