force-app/main/default/objects/AsyncFunctionInvocationRequest__c/AsyncFunctionInvocationRequest__c.object-meta.xml
<CustomObject>
    <label>Async Function Invocation Request</label>
    <nameField>
        <displayFormat>AFIR-{0000}</displayFormat>
        <label>AsyncFunctionInvocationRequest Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Function Invocation Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AsyncFunctionInvocationRequest__c/fields/AsyncInvocationJobId__c.field-meta.xml
<CustomField>
    <fullName>AsyncInvocationJobId__c</fullName>
    <label>Async Invocation Job Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AsyncFunctionInvocationRequest__c/fields/Callback__c.field-meta.xml
<CustomField>
    <fullName>Callback__c</fullName>
    <label>Callback</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AsyncFunctionInvocationRequest__c/fields/CallbackType__c.field-meta.xml
<CustomField>
    <fullName>CallbackType__c</fullName>
    <label>CallbackType</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/AsyncFunctionInvocationRequest__c/fields/Context__c.field-meta.xml
<CustomField>
    <fullName>Context__c</fullName>
    <label>Context</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AsyncFunctionInvocationRequest__c/fields/ExtraInfo__c.field-meta.xml
<CustomField>
    <fullName>ExtraInfo__c</fullName>
    <label>ExtraInfo</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AsyncFunctionInvocationRequest__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <label>Request</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AsyncFunctionInvocationRequest__c/fields/RequestId__c.field-meta.xml
<CustomField>
    <fullName>RequestId__c</fullName>
    <label>RequestId</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AsyncFunctionInvocationRequest__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AsyncFunctionInvocationRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AsyncFunctionInvocationRequest__c/fields/StatusCode__c.field-meta.xml
<CustomField>
    <fullName>StatusCode__c</fullName>
    <label>StatusCode</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/tests/InvokeJavaFunctionTest.cls
/**
 * Tests for InvokeJavaFunction.  Test assumes that FunctionReference_mdt records are deployed.
 */
@isTest
public class InvokeJavaFunctionTest {
    
    @isTest
    static void testInvoke_sync() {
        String responseBody = '{}';
        Test.setMock(HttpCalloutMock.class, FunctionInvocationCalloutMocks.respondSuccess(responseBody));

        Test.startTest();        

        FunctionInvocation invocation = InvokeJavaFunction.invokeSyncWork(new FunctionsTestAuthProviderMocks.FakeAuthProvider());

        Test.stopTest();

        Assert.areEqual(responseBody, invocation.getResponse(), invocation.getResponse());
        Assert.isNotNull(invocation.getError());
        Assert.isTrue(String.isEmpty(invocation.getError().getMessage()), invocation.getError().getMessage());
        Assert.areEqual(FunctionInvocationStatus.SUCCESS.name(), invocation.getStatus().name());                
        Assert.isNotNull(invocation.getInvocationId());
        Assert.isNull(invocation.getAsyncFunctionInvocationRequestId());
        Assert.isFalse(invocation.isFunctionError());
        Assert.areEqual(763, invocation.getExecTimeMs());
        Assert.isNotNull(invocation.getStacktrace());
        Assert.areEqual(200, invocation.getStatusCode());
    }

    @isTest
    static void testInvoke_async() {
        String responseBody = '{}';
        Test.setMock(HttpCalloutMock.class, FunctionInvocationCalloutMocks.asyncRespondSuccess());
        
        Test.startTest();

        String callbackName = 'testInvoke_async' + Datetime.now().getTime();
        FunctionInvocation invocation = 
            InvokeJavaFunction.invokeAsyncWork(callbackName, new FunctionsTestAuthProviderMocks.FakeAuthProvider());        
        Assert.isNotNull(invocation);        
        Assert.isNull(invocation.getResponse());
        Assert.isNull(invocation.getError());
        Assert.areEqual(FunctionInvocationStatus.PENDING.name(), invocation.getStatus().name());
        Assert.isNotNull(invocation.getInvocationId());
        Assert.isNotNull(invocation.getAsyncFunctionInvocationRequestId());

        // Validate AsyncFunctionInvocationRequest__c
        AsyncFunctionInvocationRequest__c afir = [SELECT Id, AsyncInvocationJobId__c, Callback__c, CallbackType__c, 
                                                         Context__c, ExtraInfo__c, Request__c, RequestId__c, 
                                                         Response__c, Status__c, StatusCode__c 
                                                  FROM AsyncFunctionInvocationRequest__c 
                                                  WHERE Id =:invocation.getAsyncFunctionInvocationRequestId()];
        Assert.isNotNull(afir);
        Assert.isNotNull(afir.Id);
        Assert.isNotNull(afir.AsyncInvocationJobId__c);
        Assert.isNotNull(afir.Callback__c);
        Assert.isNotNull(afir.CallbackType__c);
        Assert.isTrue(afir.CallbackType__c.contains('Callback'));
        Assert.isNull(afir.ExtraInfo__c);
        Assert.areEqual('{}', afir.Request__c);
        Assert.isNotNull(afir.RequestId__c);
        Assert.isTrue(afir.RequestId__c.contains(InvokeJavaFunction.FUNCTION_NAME));
        Assert.isNull(afir.Response__c);
        Assert.areEqual(FunctionInvocationStatus.PENDING.name(), afir.Status__c);
        Assert.isNull(afir.StatusCode__c);

        // Simulate function response
        afir.ExtraInfo__c = FunctionInvocationCalloutMocks.EXTRA_INFO_SUCCESS;
        afir.Response__c = responseBody;
        afir.Status__c = FunctionInvocationStatus.SUCCESS.name();
        afir.StatusCode__c = 200;
        Database.SaveResult result = Database.update(afir, false);
        Assert.isTrue(result.isSuccess());
        Assert.isNotNull(result.id);
        Assert.isNotNull(result.id, invocation.getAsyncFunctionInvocationRequestId());

        Test.stopTest();

        // Validate callback
        String whereLike = '%' + callbackName + '%';
        Account acct = [SELECT Id, Name, Description 
                        FROM Account 
                        WHERE Name LIKE :whereLike 
                        ORDER BY CreatedDate DESC limit 1];
        Assert.isNotNull(acct);
        Assert.isNotNull(acct.Name);
        Assert.isTrue(acct.Name.contains(callbackName), acct.Name);
        Assert.isNotNull(acct.Description);
        Assert.isTrue(acct.Description.contains('SUCCESS'), acct.Description);
        Assert.isTrue(acct.Description.contains('ExecTimeMs: 763'), acct.Description);
        Assert.isTrue(acct.Description.contains('FunctionError?: false'), acct.Description);
        Assert.isTrue(acct.Description.contains('Stacktrace: ()'), acct.Description);
    }
}