force-app/main/default/objects/FunctionReference__mdt/FunctionReference__mdt.object-meta.xml
<CustomObject>
    <label>Function Reference</label>
    <pluralLabel>Function References</pluralLabel>
</CustomObject>

force-app/main/default/objects/FunctionReference__mdt/fields/Certificate__c.field-meta.xml
<CustomField>
    <fullName>Certificate__c</fullName>
    <defaultValue>&quot;Functions_Cert&quot;</defaultValue>
    <label>Certificate</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FunctionReference__mdt/fields/ConsumerId__c.field-meta.xml
<CustomField>
    <fullName>ConsumerId__c</fullName>
    <label>ConsumerKey</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/functions/FunctionsMetadataAuthProvider.cls
public class FunctionsMetadataAuthProvider implements FunctionsAuthProvider {
    
    private FunctionReference__mdt functionReference;
    
    public FunctionsMetadataAuthProvider(FunctionReference__mdt functionReference) {
        this.functionReference = functionReference;
    }
    
    public String generateToken() {        
		String tokenEndPoint = URL.getSalesforceBaseURL().toExternalForm() + '/services/oauth2/token';

        String audience = 'https://login.salesforce.com';
        Organization org = [SELECT IsSandbox FROM Organization];
        if (org.IsSandbox) {
            audience = 'https://test.salesforce.com';
        }
        
		Auth.JWT jwt = new Auth.JWT();
		jwt.setSub(UserInfo.getUserName());
		jwt.setAud(audience);  //'3MVG9MwiKwcReohz8QkMzSy9xZYq7bA9OgEgrB.8mYEIj8mQqJCEnhANn.Tvqeyihvz92XkzlAbbIFrJiVsOi';
		jwt.setIss(functionReference.ConsumerId__c);
		Auth.JWS jws = new Auth.JWS(jwt, functionReference.Certificate__c);
		String token = jws.getCompactSerialization();

		Auth.JWTBearerTokenExchange bearer = new Auth.JWTBearerTokenExchange(tokenEndPoint, jws);
		return bearer.getAccessToken();        
    }
}